# Riegeli, file format for storing a sequence of records.

load("//tools/build_defs/license:license.bzl", "license")

package(
    default_applicable_licenses = ["//riegeli:license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    package_name = "riegeli",
)

licenses(["notice"])

exports_files(["LICENSE"])
