package(
    default_visibility = ["//visibility:public"],
    features = ["header_modules"],
)

licenses(["notice"])

cc_library(
    name = "highwayhash_digester",
    hdrs = ["highwayhash_digester.h"],
    deps = ["//riegeli/digests:highwayhash_digester"],
)
